llm:
  api: "sncloud" #  set either sncloud or sambastudio
  max_tokens_to_generate: 500
  temperature: 0.0
  coe: True
  select_expert: "llama3-405b"

use_cases:
  - General Assistant
  - Document Search
  - Product Selection
  - Code Generation
  - Summarization
  - Question & Answering
  - Query decomposition

models:
  Llama2:
    Model Architecture: "Advanced architecture with Grouped-Query Attention, optimized for alignment with human preferences."
    Architecture Prompting Implications: "Prompts should be structured to take advantage of its supervised fine-tuning and reinforcement learning from human feedback. Prompts that are more aligned with human conversational styles and preferences work well."
    Heuristic Guidance: "Llama 2 responds effectively to concise system prompts that direct its persona or response boundaries. This includes prompts like \"Act as if…\", \"You are…\", \"Always/Never…\", or \"Speak like…\". "
    References: "https://replicate.com/blog/how-to-prompt-llama\nhttps://arxiv.org/pdf/2307.09288.pdf\nhttps://huggingface.co/blog/llama2#how-to-prompt-llama-2\nhttps://huggingface.co/docs/transformers/main/model_doc/llama2"
    Meta Tag Format: "[INST] <<SYS>>  \n{system_prompt}  \n<</SYS>>  \n{user_prompt}  \n[/INST]"
  Llama3:
    Model Architecture: "Advanced architecture with Grouped-Query Attention, optimized for alignment with human preferences."
    Architecture Prompting Implications: "Prompts should be structured to take advantage of its supervised fine-tuning and reinforcement learning from human feedback. Prompts that are more aligned with human conversational styles and preferences work well."
    Heuristic Guidance: "Llama 3 responds effectively to concise system prompts that direct its persona or response boundaries. This includes prompts like \"Act as if…\", \"You are…\", \"Always/Never…\", or \"Speak like…\". "
    References: "https://llama.meta.com/docs/model-cards-and-prompt-formats/meta-llama-3/\nhttps://ai.meta.com/blog/meta-llama-3/\nhttps://arxiv.org/pdf/2407.21783\nhttps://huggingface.co/meta-llama/Meta-Llama-3-8B"
    Meta Tag Format: "<|begin_of_text|><|start_header_id|>system<|end_header_id|>{system_prompt}<|eot_id|>  \n<|start_header_id|>user<|end_header_id|>{user_prompt}<|eot_id|>  \n<|start_header_id|>assistant<|end_header_id|>"
  