sambastudio:
  snapi_path: ""
  rdu_arch: "sn40"

checkpoints:
  - model_name: "HermesProInstructV10"
    publisher: "NousResearch"
    description: "HermesProInstructV10 for BYOC"
    param_count: 8 # number in billions of parameters
    model_arch: "llama" #leave it blank and run byoc.find_config_params if not sure
    seq_length: 8192 #leave it blank and run byoc.find_config_params if not sure
    vocab_size: 128256 #leave it blank and run byoc.find_config_params if not sure
    checkpoint_path: "./models/models--NousResearch--Hermes-2-Theta-Llama-3-8B/snapshots/57a73110702e7b05ba3f39fef36297454c680725"
    app_id: "61fa0993-04a2-42ca-9db1-1eff693ea978"

composite_model:
  model_name:  "TestByocCoE"
  description: "CoE including byoc Hermes"
  rdu_required: 8
  model_list:
    - "HermesProInstructV10"
    - "Meta-Llama-3-8B-Instruct"

#deployment:
project: 
  project_name: "example-byoc-project"
  project_description: "this project will be used to test e2e fine-tuning pipeline implementation"
endpoint:
  endpoint_name: "test-endpoint-byoc"
  endpoint_description: "endpoint for byoc testing"
  endpoint_instances: 1
  hyperparams: null